"""race catalog + athlete race fields

Revision ID: 347bda160c86
Revises: 93fb7516cb22
Create Date: 2026-06-26 09:04:45.762992
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '347bda160c86'
down_revision: Union[str, None] = '93fb7516cb22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('distance', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cutoff_swim_s', sa.Integer(), nullable=True),
    sa.Column('cutoff_bike_s', sa.Integer(), nullable=True),
    sa.Column('cutoff_finish_s', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_slug'), ['slug'], unique=True)

    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('race_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('race_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('race_distance', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('cutoff_swim_s', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cutoff_bike_s', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cutoff_finish_s', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_athlete_race_id_race", 'race', ['race_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.drop_constraint("fk_athlete_race_id_race", type_='foreignkey')
        batch_op.drop_column('cutoff_finish_s')
        batch_op.drop_column('cutoff_bike_s')
        batch_op.drop_column('cutoff_swim_s')
        batch_op.drop_column('race_distance')
        batch_op.drop_column('race_date')
        batch_op.drop_column('race_name')
        batch_op.drop_column('race_id')

    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_slug'))

    op.drop_table('race')
    # ### end Alembic commands ###
