"""initial schema

Revision ID: 93fb7516cb22
Revises: 
Create Date: 2026-06-26 08:30:05.417019
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '93fb7516cb22'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('sport', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('moving_time', sa.Integer(), nullable=True),
    sa.Column('elapsed_time', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('avg_power', sa.Float(), nullable=True),
    sa.Column('weighted_power', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('max_hr', sa.Float(), nullable=True),
    sa.Column('avg_speed', sa.Float(), nullable=True),
    sa.Column('elevation_gain', sa.Float(), nullable=True),
    sa.Column('has_power_meter', sa.Integer(), nullable=True),
    sa.Column('tss', sa.Float(), nullable=True),
    sa.Column('intensity_factor', sa.Float(), nullable=True),
    sa.Column('tss_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_duplicate', sa.Integer(), nullable=True),
    sa.Column('primary_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_sport'), ['sport'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_start_date'), ['start_date'], unique=False)

    op.create_table('athlete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strava_athlete_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('strava_access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('strava_refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('strava_token_expires_at', sa.BigInteger(), nullable=True),
    sa.Column('ftp', sa.Float(), nullable=True),
    sa.Column('threshold_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('threshold_pace_run', sa.Float(), nullable=True),
    sa.Column('css_swim', sa.Float(), nullable=True),
    sa.Column('weekly_hours_target', sa.Float(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrics_daily',
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tss', sa.Float(), nullable=True),
    sa.Column('ctl', sa.Float(), nullable=True),
    sa.Column('atl', sa.Float(), nullable=True),
    sa.Column('tsb', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('race_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('weeks_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planned_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sport', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('structure_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('planned_tss', sa.Float(), nullable=True),
    sa.Column('intensity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fit_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('zwo_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('matched_activity_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planned_workouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planned_workouts_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_planned_workouts_plan_id'), ['plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planned_workouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planned_workouts_plan_id'))
        batch_op.drop_index(batch_op.f('ix_planned_workouts_date'))

    op.drop_table('planned_workouts')
    op.drop_table('plan')
    op.drop_table('metrics_daily')
    op.drop_table('athlete')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_start_date'))
        batch_op.drop_index(batch_op.f('ix_activities_sport'))

    op.drop_table('activities')
    # ### end Alembic commands ###
