"""multi-user: athlete_id partitioning

Adds athlete_id ownership to activities / plan / planned_workouts (backfilled to
athlete 1 for the existing single-tenant data), a unique index on
athlete.strava_athlete_id (login identity), and rebuilds metrics_daily with a
composite (athlete_id, date) primary key. metrics_daily is derived data
(regenerated by repo.rebuild_metrics), so it is recreated rather than migrated.

Revision ID: 9b56baa5ad9e
Revises: 347bda160c86
Create Date: 2026-06-26 09:44:44
"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "9b56baa5ad9e"
down_revision: Union[str, None] = "347bda160c86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_OWNED = ("activities", "plan", "planned_workouts")


def upgrade() -> None:
    # 1) Add athlete_id to owned tables: nullable → backfill to 1 → NOT NULL + FK + index.
    for table in _OWNED:
        with op.batch_alter_table(table) as b:
            b.add_column(sa.Column("athlete_id", sa.Integer(), nullable=True))
        op.execute(sa.text(f"UPDATE {table} SET athlete_id = 1"))
        with op.batch_alter_table(table) as b:
            b.alter_column("athlete_id", existing_type=sa.Integer(), nullable=False)
            b.create_index(b.f(f"ix_{table}_athlete_id"), ["athlete_id"], unique=False)
            b.create_foreign_key(
                f"fk_{table}_athlete_id_athlete", "athlete", ["athlete_id"], ["id"], ondelete="CASCADE"
            )

    # 2) Login identity: unique index on strava_athlete_id.
    with op.batch_alter_table("athlete") as b:
        b.create_index(b.f("ix_athlete_strava_athlete_id"), ["strava_athlete_id"], unique=True)

    # 3) metrics_daily — derived data; recreate with composite PK.
    op.drop_table("metrics_daily")
    op.create_table(
        "metrics_daily",
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("date", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tss", sa.Float(), nullable=True),
        sa.Column("ctl", sa.Float(), nullable=True),
        sa.Column("atl", sa.Float(), nullable=True),
        sa.Column("tsb", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["athlete_id"], ["athlete.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("athlete_id", "date"),
    )


def downgrade() -> None:
    op.drop_table("metrics_daily")
    op.create_table(
        "metrics_daily",
        sa.Column("date", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tss", sa.Float(), nullable=True),
        sa.Column("ctl", sa.Float(), nullable=True),
        sa.Column("atl", sa.Float(), nullable=True),
        sa.Column("tsb", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("date"),
    )
    with op.batch_alter_table("athlete") as b:
        b.drop_index(b.f("ix_athlete_strava_athlete_id"))
    for table in reversed(_OWNED):
        with op.batch_alter_table(table) as b:
            b.drop_constraint(f"fk_{table}_athlete_id_athlete", type_="foreignkey")
            b.drop_index(b.f(f"ix_{table}_athlete_id"))
            b.drop_column("athlete_id")
